routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::group(['prefix' => 'admin' , 'as' => 'admin.'], function (){
    Route::get('search', 'ProductController@search');
    Route::resource('products', 'ProductController', ['names' => 'products'] );
});

app/Models/Category.php
<?php

namespace App\Models;

use App\Repositories\ProductService;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = [
        'name'
    ];



    public function products()
    {
        return $this->hasMany(Product::class);
    }
}

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $fillable = [
        'name',
        'price',
        'category_id',
    ];




    public function category()
    {
        return $this->belongsTo(Category::class);
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use OwenIt\Auditing\Contracts\Auditable;


class User extends Authenticatable implements Auditable
{
    use Notifiable,
        \OwenIt\Auditing\Auditable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreProductRequest;
use App\Models\Category;
use App\Models\Product;
use App\Repositories\CategoryService;
use App\Repositories\ProductService;
use App\Services\Product\CreatingProductService;
use App\Services\Product\SearchService;
use Illuminate\Http\Request;
use Exception;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\View;

class ProductController extends Controller {

    protected $repo;

    public function __construct(ProductService $repo) {
        $this->repo = $repo;
    }

    /**
     * Display a listing of the resource.
     *
     */
    public function index(){
        $products = $this->repo->get();
        return view('admin.products.index', compact('products'));
    }


    /**
     * Display a listing of the resource.
     *
     */
    public function search(SearchService $service){
        $products = $service->execute();
        return view('admin.products.index', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     */
    public function create(CategoryService $service){

        $product = new Product;
        $categories = $service->pluck('name', 'id');

        return view('admin.products.create', compact('product', 'categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     *
     */
    public function store(CreatingProductService $service, StoreProductRequest $request){
        return  $service->execute();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     *
     */
    public function show($id){
        return view('admin.products.show')->with(['product'=>$this->repo->get($id)]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     *
     */
    public function destroy($id){
        try{
            $this->repo->delete($id);
            return redirect()->route('admin.products.index')->withMessage(trans('crud.record_deleted'));
        } catch (Exception $ex) {
            return redirect()->route('admin.products.index')->withErrors($ex->getMessage());
        }
    }
}

resources/views/admin/categories/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <div class="card">

                <form action="{{ route('admin.categories.store') }}" role="form" method="POST"  enctype="multipart/form-data">
                    {{ csrf_field() }}

                    <div class="card-header">
                        <h5><!-- insert title here --></h5>
                        @lang('crud.create_headline')
                    </div>

                    <div class="card-body">
                        
                        @include('crudable::notifications')
                    
                    </div>

                    <div class="card-footer">

                        <div class="row">

                            <div class="col-sm-6">
                                <a href="{{ route('admin.categories.index') }}" class="btn btn-danger">{{ trans('crud.cancel') }}</a>
                            </div>

                            <div class="col-sm-6 text-right">
                                <button type="submit" class="btn btn-success">{{ trans('crud.save') }}</button>
                            </div>

                        </div>

                    </div>

                </form>

            </div>
        </div>

    </div>
</div>
@stop

resources/views/admin/categories/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <div class="card">

                <form action="{{ route('admin.categories.update',$category->id) }}" role="form" method="POST"  enctype="multipart/form-data">
                    {{ csrf_field() }}
                    {{method_field('PUT')}}

                    <div class="card-header">
                        <h5><!-- insert title here --></h5>
                        @lang('crud.edit_headline')
                    </div>

                    <div class="card-body">
                        
                        @include('crudable::notifications')
                        
                    </div>

                    <div class="card-footer">

                        <div class="row">

                            <div class="col-sm-6">
                                <a href="{{ route('admin.categories.index') }}" class="btn btn-danger">{{ trans('crud.cancel') }}</a>
                            </div>

                            <div class="col-sm-6 text-right">
                                <button type="submit" class="btn btn-success">{{ trans('crud.save') }}</button>
                            </div>

                        </div>

                    </div>

                </form>

            </div>
        </div>

    </div>
</div>
@stop

resources/views/admin/categories/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-sm-6">
                            <h5><!-- insert title here --></h5>
                        </div>
                        <div class="col-sm-6 text-right">
                            <a href="{{ route('admin.categories.create') }}" class="btn btn-light btn-sm">
                                @lang('crud.create_button')
                            </a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    @include('crudable::notifications')
                    @if($categories->isEmpty())
                    @lang('crud.no_entries')
                    @else
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th scope="col"></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($categories as $category)
                            <tr>
                                <td class="text-right">
                                    <div class="btn-group" role="group">
                                        <a class="btn btn-sm btn-primary" href="{{ route('admin.categories.edit',$category->id) }}">
                                            <i class="glyphicon glyphicon-pencil"></i> @lang('crud.edit')
                                        </a>
                                        <form class="btn-group"
                                            action="{{ route('admin.categories.destroy',$category->id) }}"
                                            method="POST">
                                            {{ csrf_field() }}
                                            {{ method_field('DELETE') }}
                                            <button class="btn btn-sm btn-danger"
                                                    type="submit"><i class="glyphicon glyphicon-trash"></i> @lang('crud.delete')</button>
                                        </form>
                                    </div>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>
@stop

resources/views/admin/layouts.blade.php
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>Vom Kickstart</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/css/bootstrap.min.css">
</head>
<body>

@yield('content')

</body>
</html>

resources/views/admin/products/create.blade.php
@extends('admin.layouts')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-sm-12">

                <h1>Create new Product</h1>
                @include('crudable::notifications')
                <div class="card">
                    {!! Form::model($product, ['action' => 'ProductController@store']) !!}
                    <div class="form-group">
                        {!! Form::label('name', 'Name') !!}
                        {!! Form::text('name', '', ['class'=>'form-control']) !!}
                    </div>
                    <div class="form-group">
                        {!! Form::label('price', 'Price') !!}
                        {!! Form::number('price', '', ['class' => 'form-control']) !!}
                    </div>

                    <div class="form-group">
                        {!! Form::label('category_id', 'Category') !!}
                        {!!  Form::select('category_id', $categories, null,['class' => 'form-control'])  !!}
                    </div>


                    <div class="card-footer">

                        <div class="row">
                            <div class="col-sm-6 text-right">
                                {!! Form::submit('Save', ['class'=>'btn btn-success']) !!}
                            </div>

                        </div>

                    </div>
                    {!! Form::close() !!}
                </div>
            </div>

        </div>
    </div>
@stop

resources/views/admin/products/index.blade.php
@extends('admin.layouts')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h1>Product Catalog</h1>
                    <div class="row">
                        <div class="col-sm-6">
                            <h5><!-- insert title here --></h5>
                        </div>
                        <div class="col-sm-6 text-right">
                            <a href="{{ route('admin.products.create') }}" class="btn btn-light btn-sm">
                                @lang('crud.create_button')
                            </a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    {!! Form::model($products, ['action' => 'ProductController@search', 'method'=> 'GET']) !!}
                    <div class="form-group">
                        {!! Form::text('query', '', ['placeholder' => 'search','class'=>'form-control']) !!}
                    </div>
                    <div class="card-footer">

                        <div class="row">
                            <div class="col-sm-6 text-right">
                                {!! Form::submit('Search', ['class'=>'btn btn-success']) !!}
                            </div>

                        </div>

                    </div>
                    {!! Form::close() !!}
                    @include('crudable::notifications')
                    @if($products->isEmpty())
                    @lang('crud.no_entries')
                    @else
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th scope="col"></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($products as $product)

                            <tr>
                                <td> <a href="{{ route('admin.products.show',$product->id) }}">{{$product->name}}</a></td>
                                <td class="text-right">
                                    <div class="btn-group" role="group">
                                        <form class="btn-group"
                                            action="{{ route('admin.products.destroy',$product->id) }}"
                                            method="POST">
                                            {{ csrf_field() }}
                                            {{ method_field('DELETE') }}
                                            <button class="btn btn-sm btn-danger"
                                                    type="submit"><i class="glyphicon glyphicon-trash"></i> @lang('crud.delete')</button>
                                        </form>
                                    </div>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>
@stop

resources/views/admin/products/show.blade.php
@extends('admin.layouts')

@section('content')

    <h1>Product details</h1>
    <div class="card-body">
        <h2>{{$product->name}}</h2>
        <h2>{{$product->price}}</h2>
        <h2>{{$product->category->name}}</h2>
    </div>

    @stop